services:
  backend:
    build: backend/.
    ports:
      - "8000:8000" # Corrected port mapping syntax
  frontend:
    build: frontend/.
    ports:
      - "5173:5173" # Corrected port mapping syntax
